import { Metadata } from 'next';
import Link from 'next/link';

const SITE_URL = 'https://anime-review-site.vercel.app';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Privacy Policy for AnimeInsight. Learn how we handle your personal information, use of cookies, Google Analytics, Google AdSense, and third-party services.',
  alternates: { canonical: `${SITE_URL}/privacy/` },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-8 relative z-10">
      <nav className="text-xs text-gray-600 mb-4">
        <Link href="/" className="hover:text-[#ff3a4f] transition-colors">Home</Link>
        <span className="mx-1">/</span>
        <span className="text-gray-500">Privacy Policy</span>
      </nav>

      <h1 className="text-2xl md:text-3xl font-black text-white mb-8">
        Privacy Policy
      </h1>

      <div className="anime-panel p-6 md:p-8 space-y-8 text-[0.9375rem] leading-relaxed text-gray-400">
        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Personal Information
          </h2>
          <p>
            AnimeInsight (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) respects your privacy. We do not
            collect personal information unless you voluntarily provide it through our contact
            page or email. Any personal information you provide will be used solely to respond
            to your inquiry and will not be shared with third parties without your consent,
            except as required by law.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Google Analytics
          </h2>
          <p>
            This website uses Google Analytics, a web analytics service provided by Google LLC.
            Google Analytics uses cookies to help analyze how visitors use the site. The
            information generated by the cookie about your use of the website (including your
            IP address) will be transmitted to and stored by Google on servers in the United
            States. Google will use this information for the purpose of evaluating your use of
            the website, compiling reports on website activity, and providing other services
            relating to website activity and internet usage.
          </p>
          <p className="mt-2">
            You can opt out of Google Analytics by installing the{' '}
            <a
              href="https://tools.google.com/dlpage/gaoptout"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#00d4ff] hover:underline"
            >
              Google Analytics Opt-out Browser Add-on
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Google AdSense and Cookies
          </h2>
          <p>
            This website uses Google AdSense, a service provided by Google LLC, to display
            advertisements. Google AdSense uses cookies, including the DoubleClick cookie, to
            serve ads based on your prior visits to this website or other websites. You may opt
            out of personalized advertising by visiting{' '}
            <a
              href="https://www.google.com/settings/ads"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#00d4ff] hover:underline"
            >
              Google Ads Settings
            </a>.
          </p>
          <p className="mt-2">
            Third-party vendors, including Google, use cookies to serve ads based on your
            previous visits. You can opt out of third-party vendor cookies for personalized
            advertising by visiting{' '}
            <a
              href="https://www.aboutads.info/choices/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#00d4ff] hover:underline"
            >
              aboutads.info
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Third-Party Advertisers
          </h2>
          <p>
            Some of the ads on this site may be served by third-party advertising companies.
            These companies may use information (not including your name, address, email
            address, or telephone number) about your visits to this and other websites to
            provide advertisements about goods and services of interest to you.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Affiliate Programs
          </h2>
          <p>
            AnimeInsight participates in affiliate marketing programs, including A8.net and
            Moshimo Affiliate, which means we may earn commissions on qualifying purchases
            made through links on this website. This does not affect the price you pay for
            any products or services. We only recommend products and services that we believe
            will add value to our readers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Disclaimer
          </h2>
          <p>
            The content provided on AnimeInsight is for informational and entertainment
            purposes only. While we strive to provide accurate and up-to-date information,
            we make no warranties or representations regarding the completeness, accuracy,
            or reliability of any content on this site. All anime/manga images, trademarks,
            and copyrights belong to their respective owners.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Changes to This Policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time. Any changes will be posted
            on this page with an updated effective date. We encourage you to review this page
            periodically for the latest information.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3 border-l-4 border-[#ff3a4f] pl-3">
            Contact
          </h2>
          <p>
            If you have any questions about this Privacy Policy, please contact us via our{' '}
            <Link href="/contact/" className="text-[#00d4ff] hover:underline">
              Contact page
            </Link>.
          </p>
        </section>

        <p className="text-sm text-gray-600 pt-4 border-t border-[#252538]">
          Effective date: March 11, 2026
        </p>
      </div>
    </div>
  );
}
